apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: etc/mongo-credentials/MONGO_ROOT_PASSWORD
        volumeMounts:
        - name: secret
          mountPath:  /etc/mongo-credentials
        - name: mongodb-configmap
          mountPath: /config
        - name: persistent-volume
          mountPath: /data/db
      volumes:
      - name: persistent-volume
        persistentVolumeClaim:
          claimName: mongo-pv-claim
      - name: secret
        secret:
          secretName: mongodb-secret
      - name: mongodb-configmap
        configMap:
          name: mongodb-standalone
          items:
          - key: mongo.conf
            path: mongo.conf