version: '3.7'
services:
  item-db:
    container_name: item-db
    image: mongo:3
    restart: always
    volumes:
      - app-db:/data/db

  item-app:
    container_name: item-app
    restart: always
    image: sulaiman28/item-app:v1
    depends_on:
      - item-db
    ports:
      - "80:8080"

volumes:
  app-db:
