version: '3.7'
services:
  item-db:
    container_name: item-db
    image: mongo:3
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=my-username
      - MONGO_INITDB_ROOT_PASSWORD=my-root-password
    volumes:
      - app-db:/data/db

  item-app:
    container_name: item-app
    restart: always
    image: item-app
    depends_on:
      - item-db
    ports:
      - "8080:8080"

volumes:
  app-db:
