apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app
  labels: 
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: ghcr.io/aifai/order-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
            - name: NODE_ENV
              value: 'production'
            - name: AMQP_URL
              value: 'amqp://guest:guest@rabbitmq:5672'
               
