apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs
spec:
  selector:
    matchLabels:
      app: karsajobs
  replicas: 1
  template:
    metadata: 
      labels: 
        app: karsajobs
    spec:
      containers:
      - name: karsajobs
        image: ghcr.io/aifai/karsajobs
        command:
        ports:
          - containerPort: 8080
        env:
        - name: APP_PORT
          value: "8080"
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_ROOT_PASSWORD