apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
spec:
  selector:
    matchLabels:
      app: karsajobs-ui
  replicas: 1
  template:
    metadata: 
      labels: 
        app: karsajobs-ui
    spec:
      containers:
      - name: karsajobs-ui
        image: ghcr.io/aifai/karsajobs-ui
        command:
        ports:
          - containerPort: 8000